// Generated by https://jsonschema.net/
export const schema = {
  "quantity" : "100",
  "required": {
				"User-Name" : "Required", 
				"Password" : "Required",
				"Security-Question" : [
										"What is your pet name?", 
										"What was the name of your first school?",
										"Who was your Childhood hero?",
										"What is your favorite past-time?",
										"What is your all time favorite sports team",
										"What is your Fathers midddle name?",
										"What make was your first car or bike?",
										"Where did you first meet your spouse?"
									],
				"Security Answer": "Required", 
				"Preferred Language" : [
										"Hindi", "Englsh"
										],
				"Personal Details" : {
										"Name" :["First", "Middle", "Last"],
										"Gender" : ["Male", "Female", "Transgender"],
										"Date of Birth" : "Required",
										"Occupation" : ["GOVERNMENT", "PUBLIC", "PRIVATE" , "PROFESSIONAL", "SELF EMPLOYED", "STUDENT", "OTHERS"],
										"Marital Status" : ["Married", "Unmarried"],
										"Country" : "Required",
										"Email" : "Required",
										"ISD-Mobile" : "Required",
										"Nationality" : "Required"
									}, 
				"Residential Address" : {
											"Flast/Door/Block No. " : "Required",
											"Street/Lane":"Required",
											"Area/Locatity" : "Optional",
											"Pin Code" : "Required",
											"State" : "Required",
											"City/Town" : "Required",
											"Post Office" : "Required",
											"Phone" : "Required",
											"Copy Residence to office Address" : ["Yes", "NO"]
										}
			}
};